### ISSUE TITLE
[PI1] Como programadora, necesito conocer el formato del perfil de ecualización de audio compatible con Linux

### ISSUE THREAD

**Issue by agr8** [Olasergiolas/Go-AutoEQ#7]
Para poder abarcar el primer milestone, *[M1]: Release inicial*, necesito conocer qué formato y qué tipo de datos son los que deben aparecer en el perfil de ecualización que se quiere generar (#3)

**Comment by Olasergiolas** [comment]
Para mantener organización y consistencia acabo de crear una plantilla para las Issues como programador que auto-asigna el label correspondiente entre otras cosas, utilízala para issues de este tipo 👍.

**Comment by agr8** [comment]
Perfecto, así lo haré a partir de ahora. Gracias!

**Comment by Olasergiolas** [comment]
En este [Gist](https://gist.github.com/Olasergiolas/1223ef2155be0afcd02382b2577c019f) que he creado tienes un ejemplo de perfil básico de EasyEffects que solo tiene la ecualización activada, échale un vistazo.
